import ollama

response = ollama.chat(model='llama3', messages=[
  {
    'role': 'user',
    'content': '''Can you please summarize the text below and pick out the important parts:
        Mr. Don Davies (Vancouver Kingsway, NDP)
        Mr. Speaker, I move that the 19th report of the Standing Committee on Finance, presented on Monday, May 6, 2024, be concurred in.
        I would like to inform the House that I will be splitting my time with the magnificent member for 
        Report 19, ├ó┬Ç┬£Excess Profit Tax on Large Grocery Companies├ó┬Ç┬¥, was put forward by my predecessor, the former NDP finance critic, Daniel Blaikie, who said the following: 

                        
        The Canadian grocery sector's $6 billion in profits last year set a new record. Grocery prices are now rising at the fastest rate in more than 40 years. At the same time, Canadians are going hungry, food insecurity is rising dramatically and demand for food banks is exceeding donations. There can be no doubt that corporate greed is resulting in higher grocery bills for Canadians.
        According to Statistics Canada, food retail profits have more than doubled since prepandemic norms, and profits continue to grow. The Competition Bureau has found that the profit margins of grocery giants are increasing and that this trend predates the supply chain disruptions faced during the pandemic and the current inflationary period.
        Loblaws has almost doubled its profit margin in the last five years, and Metro has the biggest profit margin of any grocer in Canada. Loblaws has even admitted to participating in an industry-wide price-fixing scam, yet there have been no meaningful consequences for these corporate criminals who ripped off Canadians for bread.
        While New Democrats have fought for years to make grocery giants and other corporate giants play by the rules, pay what they owe, and put the money back in people's pockets, both the Liberals and the Conservatives have refused to tackle corporate greed. In fact, the Liberals have gifted $26 million to Loblaws and Costco for new appliances. The Conservatives brought in $60 billion in corporate tax giveaways when they were last in power, and both the Liberals and the Conservatives failed to get tough on corporate criminals as their successive governments presided over an industry-wide bread price-fixing scam from 2001 to 2015.
        Due to this failure of leadership, Canadians have now taken matters into their own hands by boycotting big grocery chains. Instead of sitting on the sidelines while Canadians go hungry, it is time for the federal government to act.
        In 2022, the Liberal government agreed to bring in a one-time 15% windfall profits tax on banks and insurance firms, known as the Canada recovery dividend. There is absolutely no reason this measure should not be extended to grocery giants.
        Forcing grocery giants to pay tax on excess profits would disincentivize price gouging and encourage lower prices. It would help recoup the tax dollars that both Liberals and Conservatives have gifted to grocery giants. It would lower food costs for Canadians through a grocery rebate and an expanded national school food program.
        The finance committee report before us today is not the first time a committee has recommended an excess profits tax on grocery multinationals in this Parliament. On June 13, 2023, the Standing Committee on Agriculture presented a report to the House, which recommended the following:

                        
        On June 27, 2023, the Competition Bureau released its retail grocery market study report, which found exactly that. The report noted that the Canadian grocery industry is concentrated, and the problem is getting worse. When the Competition Act was introduced in 1986, there were at least eight large grocery chains in Canada, and each was owned by a different company. Today, most sales are happening in stores owned by five grocery giants: Loblaws, Sobeys, Metro, Costco and Walmart. Grocery prices are increasing at the fastest rate in decades, and the profits of Canada's three largest grocers, Loblaws, Metro and Sobeys, have risen significantly in recent years.
        The food gross margins of grocery giants are increasing, and this trend predates the supply chain disruptions faced during the pandemic and the current inflationary period. Even small changes in margins can be meaningful. Every percentage point increase in gross margins at grocery stores adds over $1 billion to Canadians' food bills each year. The fact that Canada's largest grocers have been able to increase these margins is a sign that there is room for more competition in Canada's grocery industry. Those were the conclusions of the Competition Bureau.
        The Competition Bureau's findings contradict previous committee testimony from grocery giants, who claimed they are not increasing profit margins on food items but instead are simply passing on higher costs from suppliers. This should come as no surprise. Canadians have every right to be skeptical of the claims made by grocery giants, as well as their commitment to corporate ethics, based on their previous conduct.
        We must never forget that in December 2017, Weston Foods and Loblaw Companies Limited confessed that they participated in what they described as an ├ó┬Ç┬£industry-wide price-fixing arrangement├ó┬Ç┬¥ to inflate retail and wholesale bread prices for Canadians. The Competition Bureau has since executed search warrants against Canada Bread, Weston Foods, Loblaws, Metro, Sobeys, Walmart Canada, Giant Tiger, Overwaitea Food Group Limited, and Maple Leaf Foods Inc.
        Despite this years-long investigation, there have been no meaningful consequences for the perpetrators of this criminal price-fixing scam. Loblaws received immunity from prosecution and offered customers $25 gift cards as compensation. Canada Bread also received leniency in sentencing after pleading guilty to four counts of price-fixing.
        Given that we still do not have clear answers on this scheme or any real consequences for these corporate misdeeds that stole bread money out of people's pockets, Canadians have understandably run out of patience. It is time for their elected leaders to step up, and that is what New Democrats are doing today. 
        An excess profits tax would not only discourage price gouging; it would also provide significant revenue to address growing rates of food insecurity and child hunger across Canada.
        Today, nearly one in four Canadian children does not get enough to eat, and more than one-third of food bank users are children. According to Children First Canada, there has been a 29% increase in food insecurity in children in the last year alone. However, Canada remains the only G7 country that does not have some form of a national school food program or national standards. This is a critical gap felt strongly in a time of skyrocketing food prices.
        After years of NDP pressure, including a bill I introduced in this House almost five years ago, the Liberals finally agreed to bring in a national school food program in budget 2024. This urgently needed program will be in place as early as the 2024-25 school year and help 400,000 children access the food they need to grow up healthy. By the way, that is nowhere near what is needed. There are over two million Canadians attending school from grades 1 to 6 in this country, and every one of them deserves a hot, nutritious meal every day they attend school.
        This is an important first step. While there are over two million children in grades 1 to 6 alone in Canada, and 2.6 million in grades 1 to 8, clearly the scale of this program is far from sufficient to reach all Canadian children. Revenues from an excess profits tax on grocery giants could be strategically used to provide more nutritious meals to more Canadian children. Based on the latest data from Statistics Canada's Canadian income survey, 8.7 million Canadians lived in food-insecure households in 2023.
        As a targeted income support, a grocery rebate would also be an important tool for addressing household food insecurity. It would recognize that inadequate income and high prices lie at the root of the challenges faced by Canadians who are unable to afford the food they need. 
        In light of the record profits made by the Canadian grocery sector, coupled with the alarming rise in food insecurity among millions of Canadians, I call on all members of the House to support the concurrence motion before us. Corporate greed cannot be allowed to drive up grocery bills while Canadians go hungry. It is time for the federal government to act decisively for Canadians and ensure fairness for all.''',
  },
])
print(response['message']['content'])